# Generated by Django 2.1.3 on 2019-12-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0003_auto_20191207_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
    ]
