# Generated by Django 3.0 on 2019-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0003_auto_20191215_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='number',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
