# Generated by Django 2.1.3 on 2019-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0005_auto_20191208_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='box_office',
            field=models.FloatField(blank=True, null=True, verbose_name='Box Office'),
        ),
    ]
