# Generated by Django 2.1.3 on 2019-12-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0007_systemuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
